name = "child-rewards"
main = "src/index.js"
compatibility_date = "2026-07-11"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
NOTION_GIFTS_DATABASE_ID = "39a86019-c92c-81a4-b432-ca254a0e3de2"
NOTION_TASKS_DATABASE_ID = "39a86019-c92c-8188-a5e8-c382a8ebc591"
NOTION_LEDGER_DATABASE_ID = "39a86019-c92c-8175-a929-f262bc580584"
NOTION_TASK_DONE_STATUS_ID = "068232b4-437e-472c-b9bb-62e2b266d266"
NOTION_VERSION = "2022-06-28"

[[routes]]
pattern = "child.malinkang.com"
custom_domain = true
