name = "child-rewards"
main = "src/index.js"
compatibility_date = "2026-07-11"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
NOTION_GIFTS_DATABASE_ID = "39a86019-c92c-81a4-b432-ca254a0e3de2"
NOTION_TASKS_DATABASE_ID = "39a86019-c92c-8188-a5e8-c382a8ebc591"
NOTION_LEDGER_DATABASE_ID = "39a86019-c92c-8175-a929-f262bc580584"
NOTION_BALANCE_DATABASE_ID = "39d86019-c92c-81dc-b9b8-e0aeb22afbae"
NOTION_BALANCE_PAGE_ID = "39d86019-c92c-8191-9020-fa86ecd13ac4"
NOTION_CHILD_PROFILE_DATABASE_ID = "3a086019-c92c-819d-855b-f36580c0203f"
NOTION_CHILD_PROFILE_PAGE_ID = "3a086019-c92c-81ad-be95-c0829a5a260b"
NOTION_COURSES_DATABASE_ID = "3a086019-c92c-81d4-adc6-caab4eeecedb"
NOTION_CLASS_RECORDS_DATABASE_ID = "3a086019-c92c-817d-ab38-ed41a0417036"
NOTION_VERSION = "2022-06-28"

[[routes]]
pattern = "child.malinkang.com"
custom_domain = true
